[project]
name = "django-exercises"
version = "0.1.0"
description = "Mugna Tech internship Django exercises"
authors = [
    {name = "GabLitob",email = "litobangelgabrieljr@gmail.com"}
]
requires-python = ">=3.12"
dependencies = [
    "django (==4.2)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
